[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = { git = "https://github.com/risc0/risc0.git", rev = "845ff76" }

[dependencies]
risc0-zkvm = { git = "https://github.com/risc0/risc0.git", rev = "845ff76", default_features = false, features = ["std"] }
proof-core = { path = "../../proof-core" }
eth_trie = { git = "https://github.com/carver/eth-trie.rs.git" }
primitive-types = { version = "0.12.1", default-features = false }
